apiVersion: v1
kind: Service
metadata:
  name: surveyform-app-service
  namespace: hw2
spec:
  selector:
    app: survey-app
  ports:
    - protocol: TCP
      port: 8080      # External port
      targetPort: 8080  # Port on your pod
  type: NodePort
